language: ruby
before_install:
  - gem install bundler
rvm:
  - 2.0
  - 2.1.0
  - 2.1
  - 2.2.0
  - 2.2.2
  - 2.2
  - 2.3.0
  - 2.3.1
  - 2.3
  - 2.4.0
  - 2.4
  - 2.5.0
  - 2.5
  - jruby
  - rbx-1
  - rbx-2
  - rbx-3

matrix:
  allow_failures:
    - rvm: 2.2.0
    - rvm: jruby
    - rvm: rbx-1
    - rvm: rbx-2
    - rvm: rbx-3

notifications:
  slack: shyftplanteam:ytcBo8O4FsF6i11yzoCmfvTU
